// src/app.tsx
import React, { FC, useContext } from 'react';

import { AssetContext, AssetLoader } from './modules/asset';
import { Debug } from './modules/debug';

export const App: FC = () => {
  const { assetState } = useContext(AssetContext);
  return (
    <>
      <div className="app">
        <style jsx>{`
          .app {
            position: relative;
            display: grid;
          }
        `}</style>
        {assetState.data ? <Debug /> : <AssetLoader />}
      </div>
      <canvas id="canvas">
        <style jsx>{`
          #canvas {
            position: absolute;
            top: 0;
            left: 0;
            z-index: -1;
            width: 1280px;
            height: 720px;
          }
        `}</style>
      </canvas>
    </>
  );
};

// app/src/App.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import AssetLoader from './modules/asset/AssetLoader.svelte';
	import { assets } from './modules/asset'
	
	let canvas: HTMLCanvasElement | null = null;
	document.body.oncontextmenu = (e) => {
		e.preventDefault();
		return false;
	};

	disableChromePerformanceBloat();

	// https://github.com/bevyengine/bevy/issues/4851
	function disableChromePerformanceBloat() {
		if (performance.clearMeasures) {
			performance.clearMeasures();
		}
		if (performance.clearMarks) {
			performance.clearMarks();
		}
	}

	let assetData: Uint8Array | null = null;
	assets.subscribe(data => {
		if (!data) return;
		assetData = data;

		if (canvas) {
			canvas.style.zIndex = '0';
			canvas.onblur = () => {
				setTimeout(() => {
					canvas?.focus();
				});
			}
			canvas.focus();
			setInterval(() => {
				if (document.activeElement !== canvas) {
					canvas?.focus();
				}
			}, 1000)
		}

		shrm.main(data);
	});

	let shrm: any;
	onMount(async () => {
		let loadedWasmModule = false;
		while (!loadedWasmModule) {
			if ((window as any).shrm) {
				loadedWasmModule = true;
				shrm = (window as any).shrm;
			} else {
				await new Promise(resolve => setTimeout(resolve, 100));
			}
		}

		const loadingIndicator = document.querySelector('#loading-indicator');
		if (loadingIndicator) {
			loadingIndicator.remove();
		}
	})
</script>

{#if assetData == null}
	<div class="app">
		<AssetLoader />
	</div>
{/if}
<canvas
	id="canvas"
	bind:this={canvas}
	on:contextmenu={(e) => { e.preventDefault(); return false; }}
/>

<style>
	.app {
		position: relative;
		display: grid;
	}
	#canvas {
		position: absolute;
		top: 0;
		left: 0;
		z-index: -1;
		width: 1280px;
		height: 720px;
	}
</style>
